# Use the official OpenJDK base image with JDK 17
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /orders-management

# Copy the Configuration Server JAR file into the container
COPY target/configurationServer-0.0.1-SNAPSHOT.jar config-server.jar

# Expose the port on which the config server will run (default is 8888)
EXPOSE 8888

# Define the entry point to run the JAR file
ENTRYPOINT ["java", "-jar", "config-server.jar"]
